url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
title: "Susan T. Parker" 
name: "Susan T. Parker"
twitter: "susan_t_parker"
twitter_url: "https://twitter.com/susan_t_parker"
github: "sparker6"
github_url: "https://github.com/sparker6"
address: "Chicago, IL"
email: "su.parker@northeastern.edu"
